version: "3.9"

services:

  db:
    image: postgres:15
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env

  web:
    build: ./server
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn server.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    ports:
      - 80:80
    depends_on:
      - web
  
  worker_1:
    build: ./workers/besplatka
    env_file:
      - ./.env
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: