# Generated by Django 4.2.1 on 2023-05-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('meta', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
    ]
