# Generated by Django 4.2.1 on 2023-05-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BountyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
            ],
        ),
    ]
