# Generated by Django 4.2.1 on 2023-05-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('work', 'Work'), ('stop', 'Stop')], default='stop', max_length=50)),
                ('params', models.TextField(blank=True, default='', help_text='Send params with space delimeter')),
            ],
        ),
    ]
